#+TITLE: Compilador
#+AUTHOR: Lucas Martins Soares
#+OPTIONS: toc:t

** Índice                                                              :toc:
  - [[#link-do-repositório][Link do Repositório]]
  - [[#como-executar][Como executar]]
  - [[#como-funciona][Como funciona]]

** Link do Repositório
[[https://github.com/lucasmsoares96/Compilador]]

** Como executar
Nesse repositório se encontra os binários pre-compilados para linux (sem extensão) e para windows (.exe) na arquitetura x86. Para executar o binário pre-compilado, basta digitar o seguinte comando:

- Linux
#+begin_src bash
cd build
./Compilador
#+end_src

- Windows
#+begin_src bash
cd build
"Compilador.exe"
#+end_src

Caso deseje executar o programa em outra arquitetura, será necessário recompilar o código. Para isso é preciso ter um ambinete haskell instalado e configurado nas suas maquina. A forma recomendada de instalação é através do [[https://www.haskell.org/ghcup/][GHCup]]. Em seguida execute o seguinte comando.

#+begin_src bash
cabal run
#+end_src

O comando acima compila e executa o programa em Haskell.

** Como funciona
Um compilador é uma ferramento capaz de traduzir o código de uma linguagem de programação para outra linguagem. Esse compilador converte um código na linguagem C para o correspondente na linguagem Python.

A compilação possui 6 etapas:
1. Análise Lexica
2. Análise Sintática
3. Análise Semântica
4. Geração de Código Intermediário
5. Otimização do Código
6. Geração do Código Final

Atualmente este compilador está na sua segunda etapa (Análise Semântica)
